Repository lucky-pocket/luckyPocket-back, pull requests merged in 2023-10, with the labels that each got.

#6 Domain usecase
  internal/domain/auth.go
  internal/domain/data/constant/enum.go
  internal/domain/data/input/.gitkeep
  internal/domain/data/input/auth_input.go
  internal/domain/data/input/game_input.go
  internal/domain/data/input/pocket_input.go
  internal/domain/data/input/user_input.go
  internal/domain/data/output/.gitkeep
  internal/domain/data/output/auth_output.go
  internal/domain/data/output/game_output.go
  internal/domain/data/output/notice_output.go
  internal/domain/data/output/pocket_output.go
  internal/domain/data/output/user_output.go
  internal/domain/example.go
  internal/domain/game.go
  internal/domain/notification.go
  internal/domain/pocket.go
  internal/domain/user.go
Labels: :one: Priority: High, :sparkler: Feature

#9 gofmt global 적용
  go.mod
  internal/domain/auth.go
  internal/domain/data/input/user_input.go
  internal/domain/data/output/notice_output.go
  internal/domain/game.go
  internal/domain/notification.go
  internal/domain/pocket.go
  internal/domain/user.go
Labels: ⚡️Simple

#11 config 추가
  .github/workflows/ci.yml
  .gitignore
  go.mod
  go.sum
  internal/global/config/.gitkeep
  internal/global/config/config.go
  internal/global/config/load.go
  makefile
  test/unit/.gitkeep
  test/unit/config/load_test.go
Labels: :sparkler: Feature, 🎨 Structure, :two: Priority: Medium

#13 Repository layer
  internal/domain/auth.go
  internal/domain/notification.go
  internal/domain/pocket.go
  internal/domain/user.go
Labels: :two: Priority: Medium

#15 transaction 추가
  .github/workflows/ci.yml
  codecov.yml
  internal/global/global.go
  internal/global/tx/multi_tx.go
  internal/global/tx/tx.go
  internal/global/tx/tx_manager.go
  resource/.mockery.yml
  test/unit/global/config/load_test.go
  test/unit/global/tx/with_tx_test.go
Labels: :sparkler: Feature, 🎨 Structure, :two: Priority: Medium

#17 auth 패키지
  internal/global/auth/info.go
  internal/global/auth/jwt/.gitkeep
  test/unit/global/auth/auth_test.go
Labels: :one: Priority: High, :sparkler: Feature, 🎨 Structure, 🧪Test

#20 jwt 패키지 추가
  go.mod
  go.sum
  internal/domain/data/constant/const.go
  internal/global/auth/info.go
  internal/global/auth/jwt/.gitkeep
  internal/global/auth/jwt/issuer.go
  internal/global/auth/jwt/parser.go
  internal/global/auth/jwt/token.go
  test/unit/global/auth/auth_test.go
  test/unit/global/auth/jwt/issue_test.go
  test/unit/global/auth/jwt/parse_test.go
Labels: :sparkler: Feature, :two: Priority: Medium

#21 User UseCase 정의
  internal/app/user/usecase/user_usecase.go
  internal/domain/data/output/mapper/.gitkeep
  internal/domain/data/output/mapper/user_mapper.go
  internal/domain/data/output/user_output.go
  internal/domain/user.go
Labels: :two: Priority: Medium

#24 fix :: notice domain name fix
  internal/domain/notice.go
Labels: :three: Priority: Low

#27 Pocket Domain UseCase 정의
  internal/app/pocket/usecase/pocket_usecase.go
  internal/domain/data/input/pocket_input.go
  internal/domain/data/output/mapper/pocket_mapper.go
  internal/domain/pocket.go
  internal/domain/user.go
Labels: :two: Priority: Medium

#32 30 notice usecase
  internal/app/notice/usecase/notice_usecase.go
  internal/domain/data/output/mapper/notice_mapper.go
  internal/domain/notice.go
Labels: :two: Priority: Medium

#33 error status
  internal/global/error/status/status.go
Labels: :two: Priority: Medium

#37 ci test job 통합
  .github/workflows/ci.yml
Labels: ⚡️Simple

#35 usecase 리팩터링
  codecov.yml
  internal/app/notice/usecase/get_notice.go
  internal/app/notice/usecase/notice_usecase.go
  internal/app/pocket/usecase/get_pocket_detail.go
  internal/app/pocket/usecase/get_user_pockets.go
  internal/app/pocket/usecase/pocket_usecase.go
  internal/app/pocket/usecase/reveal_sender.go
  internal/app/pocket/usecase/send_pocket.go
  internal/app/pocket/usecase/set_visibility.go
  internal/app/user/usecase/count_coins.go
  internal/app/user/usecase/get_my_detail.go
  internal/app/user/usecase/get_ranking.go
  internal/app/user/usecase/get_user_detail.go
  internal/app/user/usecase/user_usecase.go
  internal/domain/data/constant/const.go
  internal/domain/data/input/pocket_input.go
  internal/domain/data/input/user_input.go
  internal/domain/data/output/mapper/pocket_mapper.go
  internal/domain/data/output/mapper/user_mapper.go
  internal/domain/notice.go
  internal/domain/pocket.go
  internal/domain/user.go
  internal/global/tx/tx_manager.go
  test/stubs/stubs.go
  test/stubs/tx.go
  test/unit/domain/notice/usecase/get_notice_test.go
  test/unit/domain/notice/usecase/suite_test.go
  test/unit/domain/pocket/usecase/get_pocket_detail_test.go
  test/unit/domain/pocket/usecase/get_user_pockets_test.go
  test/unit/domain/pocket/usecase/reveal_sender_test.go
  test/unit/domain/pocket/usecase/send_pocket_test.go
  test/unit/domain/pocket/usecase/set_visibility_test.go
  test/unit/domain/pocket/usecase/suite_test.go
  test/unit/domain/user/usecase/count_coins_test.go
  test/unit/domain/user/usecase/get_my_detail_test.go
  test/unit/domain/user/usecase/get_ranking_test.go
  test/unit/domain/user/usecase/get_user_detail_test.go
  test/unit/domain/user/usecase/suite_test.go
Labels: :one: Priority: High, :recycle: Refactoring, 🧪Test

#48 46 jwtissuer expiresat
  go.sum
  internal/app/auth/usecase/auth_usecase.go
  internal/domain/data/output/mapper/auth_mapper.go
  internal/global/auth/jwt/issuer.go
  test/unit/domain/auth/usecase/login_test.go
  test/unit/domain/auth/usecase/refreshtoken_test.go
  test/unit/global/auth/jwt/issue_test.go
  test/unit/global/auth/jwt/parse_test.go
Labels: :bug: Bug, :two: Priority: Medium

#52 user repository interface 수정
  internal/app/user/repository/count.go
  internal/app/user/repository/find.go
  internal/app/user/repository/find_by_email.go
  internal/app/user/repository/find_by_id.go
  internal/app/user/repository/get_rank.go
  internal/app/user/repository/update.go
  internal/app/user/usecase/get_ranking.go
  internal/domain/data/output/user_output.go
  internal/domain/user.go
  test/.DS_Store
  test/integration/data/repository/user/find_by_name_test.go
  test/integration/data/repository/user/get_rank_test.go
  test/unit/domain/user/usecase/get_ranking_test.go
Labels: :recycle: Refactoring, :sparkler: Feature, :two: Priority: Medium, 🧪Test

#54 game usecase
  internal/app/game/usecase/game_usecase.go
  internal/domain/data/constant/const.go
  internal/domain/data/output/game_output.go
  internal/domain/data/output/mapper/game_mapper.go
  internal/domain/game.go
  test/stubs/stubs.go
  test/unit/domain/game/usecase/get_ticket_info_test.go
  test/unit/domain/game/usecase/play_yut_test.go
  test/unit/domain/game/usecase/suite_test.go
Labels: :two: Priority: Medium
